# Generated by Django 5.1.1 on 2024-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=6, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('guardian_contact', models.CharField(max_length=15)),
                ('student_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
