# Generated by Django 5.1.1 on 2024-10-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp1', '0002_studentleave_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
