# Generated by Django 5.1.1 on 2024-10-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp1', '0003_alter_studentleave_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='delete_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
