# Generated by Django 5.1.1 on 2024-10-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp1', '0004_studentleave_delete_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentleave',
            old_name='delete_data',
            new_name='deleted_time',
        ),
    ]
