# Generated by Django 5.1.1 on 2024-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp1', '0006_studentleave_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='image'),
        ),
    ]
